{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "9df8c4ad-0cdc-4bb7-a4e8-5b948e95646b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1. Completed data extraction\n",
      "2. Completed data transformation & modeling\n",
      "3. Completed Load Data to PostgreSQL\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import pandas as pd\n",
    "from sqlalchemy import create_engine\n",
    "from dotenv import load_dotenv\n",
    "\n",
    "load_dotenv()\n",
    "\n",
    "def extract_data():\n",
    "    \"\"\"\n",
    "    [E] Data Extraction step\n",
    "    Load raw data from CSV.\n",
    "    \"\"\"\n",
    "    df = pd.read_csv('ship_fuel_efficiency.csv')\n",
    "    print(\"1. Completed data extraction\")\n",
    "    return df\n",
    "\n",
    "def transform_data(df):\n",
    "    \"\"\"\n",
    "    [T] Data Transformation & modeling step\n",
    "    \"\"\"\n",
    "    df['fuel_per_nm'] = df['fuel_consumption'] / df['distance']\n",
    "    df['co2_per_nm'] = df['CO2_emissions'] / df['distance']\n",
    "    \n",
    "    ship_dimension = df[['ship_id', 'ship_type', 'fuel_type']].drop_duplicates().reset_index(drop=True)\n",
    "    \n",
    "    route_dimension = df[['route_id']].drop_duplicates().reset_index(drop=True)\n",
    "    \n",
    "    month_data = [{\"month\": m} for m in df['month'].unique()]\n",
    "    month_dimension = pd.DataFrame(month_data)\n",
    "\n",
    "    month_map = {'January': 1, 'February': 2, 'March': 3, 'April': 4, 'May': 5, 'June': 6,\n",
    "                 'July': 7, 'August': 8, 'September': 9, 'October': 10, 'November': 11, 'December': 12}\n",
    "    month_dimension['month_num'] = month_dimension['month'].map(month_map)\n",
    "\n",
    "    def fuel_grade(fuel):\n",
    "        if fuel < 21.1:\n",
    "            return 'A'\n",
    "        elif fuel < 34.2:\n",
    "            return 'B'\n",
    "        else:\n",
    "            return 'C'\n",
    "\n",
    "    def co2_grade(co2):\n",
    "        if co2 < 58.6:\n",
    "            return 'A'\n",
    "        elif co2 < 95.0:\n",
    "            return 'B'\n",
    "        else:\n",
    "            return 'C'\n",
    "\n",
    "    df['eff_grade'] = df['fuel_per_nm'].apply(fuel_grade)\n",
    "    df['co2_grade'] = df['co2_per_nm'].apply(co2_grade)\n",
    "\n",
    "    fuel_fact = df[['ship_id', 'route_id', 'month', 'distance', 'fuel_consumption', \n",
    "                    'CO2_emissions', 'weather_conditions', 'engine_efficiency', \n",
    "                    'fuel_per_nm', 'co2_per_nm', 'eff_grade', 'co2_grade']]\n",
    "\n",
    "    print(\"2. Completed data transformation & modeling\")\n",
    "    \n",
    "    return ship_dimension, route_dimension, month_dimension, fuel_fact\n",
    "    \n",
    "def load_to_postgres(ship_dimension, route_dimension, month_dimension, fuel_fact):\n",
    "    \"\"\"\n",
    "    [L] Data Loading step\n",
    "    Securely connects to PostgreSQL and loads data.\n",
    "    \"\"\"\n",
    "    db_user = os.getenv(\"DB_USER\")\n",
    "    db_password = os.getenv(\"DB_PASSWORD\")\n",
    "    db_host = os.getenv(\"DB_HOST\")\n",
    "    db_port = os.getenv(\"DB_PORT\")\n",
    "    db_name = os.getenv(\"DB_NAME\")\n",
    "    \n",
    "    engine = create_engine(f'postgresql://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}')\n",
    "    \n",
    "    ship_dimension.to_sql('ship_dimension', engine, if_exists='replace', index=False)\n",
    "    route_dimension.to_sql('route_dimension', engine, if_exists='replace', index=False)\n",
    "    month_dimension.to_sql('month_dimension', engine, if_exists='replace', index=False)\n",
    "    fuel_fact.to_sql('fuel_fact', engine, if_exists='replace', index=False)\n",
    "    print(\"3. Completed Load Data to PostgreSQL\")\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    raw_df = extract_data()\n",
    "    s_df, r_df, m_df, f_df = transform_data(raw_df)\n",
    "    load_to_postgres(s_df, r_df, m_df, f_df)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8e83811d-c050-449d-8e6d-7195683376f9",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
